# Generated by Django 3.0.2 on 2020-04-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eagle_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
