# Generated by Django 3.0.2 on 2020-04-19 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_auto_20200417_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(to='assessment.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type_answer',
            field=models.CharField(choices=[('Text', 'Text'), ('Rating', 'Rating')], default='Rating', max_length=6),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='assessment name'),
        ),
    ]
