# Generated by Django 3.0.2 on 2020-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20200419_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_rating',
            field=models.SmallIntegerField(max_length=1, null=True, verbose_name='answer rating'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='answers',
            field=models.ManyToManyField(to='assessment.Answer'),
        ),
    ]
