# Generated by Django 3.0.2 on 2020-04-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20200425_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_rating',
            field=models.SmallIntegerField(null=True, verbose_name='answer rating'),
        ),
    ]
