# Generated by Django 3.0.2 on 2020-04-25 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0006_auto_20200425_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='completed_students',
            field=models.ManyToManyField(related_name='completed_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
