# Generated by Django 3.0.2 on 2020-04-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_remove_team_team_number'),
        ('assessment', '0007_assessment_completed_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='answers',
        ),
        migrations.AddField(
            model_name='assessment',
            name='result_sets',
            field=models.ManyToManyField(to='assessment.Answer'),
        ),
        migrations.CreateModel(
            name='Result_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_answers', models.ManyToManyField(related_name='rating_answers', to='assessment.Answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_student', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Team')),
                ('text_answers', models.ManyToManyField(related_name='text_answers', to='assessment.Answer')),
            ],
        ),
    ]
