# Generated by Django 3.0.2 on 2020-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20200426_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='result_sets',
            field=models.ManyToManyField(to='assessment.Result_set'),
        ),
    ]
