# Generated by Django 3.0.2 on 2020-04-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20200426_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='open_status',
            field=models.BooleanField(default=True, verbose_name='open status'),
        ),
    ]
