# Generated by Django 3.0.2 on 2020-04-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60, verbose_name='course name')),
                ('course_code', models.IntegerField(verbose_name='course code')),
                ('section_number', models.SmallIntegerField(verbose_name='section number')),
                ('year', models.SmallIntegerField(verbose_name='year of realization')),
                ('semester', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], max_length=1, verbose_name='semester of realization')),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(verbose_name='team number')),
                ('team_name', models.CharField(max_length=60, verbose_name='team name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Course')),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
