# Generated by Django 3.0.2 on 2020-04-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_course_professor_eagle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor_eagle_id',
        ),
    ]
