# Generated by Django 3.0.2 on 2020-04-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_number',
        ),
    ]
